---
title: "Hoang's Replication"
date: October 13, 2017 
output: pdf_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# setup
install.packages("tidyverse")


library(dplyr); library(tidyr); library(knitr); library(zoo); library(sandwich); library(lmtest); library(broom); library(gmm); library(tidyverse)
data(Finance)
load("data/171013_WCData_m.RData")

# clean data to match paper time period
df.cln <- df.Hrep.m %>% 
  filter(Date >= 'Jul 1963' & Date <= 'Dec 2008')

# function
Table_Sum <- function(df) {
  # replicate MS12 Table 2

  # set ordering for sorting
  Stat.Order <- c("Mean", "Std", "Min", "Max", "Auto1") # columns vector
  Port.Order <-  colnames(df)[-1] # skip Date

    table.sum.basic <- df %>%
    summarise_each(funs(Mean=mean(., na.rm=TRUE),
                        Std=sd(., na.rm=TRUE),
                        Min=min(.),
                        Max=max(.),
                        Auto1=cor(.,lag(., 1),use="pairwise.complete.obs")),
                   -Date) %>%
    gather(variable, value) %>%
    separate(variable, c("Var", "stat"), sep = "\\_") %>%
    mutate(stat=factor(stat, levels = Stat.Order)) %>% # sort stat order
    arrange(stat) %>%
    spread(stat, value) %>%
    mutate_each(funs(sprintf("%.3f", round(.,3))), -Var) %>% # format
    mutate(Var=factor(Var, levels = Port.Order)) %>% # sort port order
    arrange(Var) # sort by column Var

  return(table.sum.basic)
}
```

# Replicate MS12 Table 2 (Summary Stats)
```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(Table_Sum(df.cln), align='c')
```
# Replicate MS12 Table 3
```{r, echo=FALSE, warning=FALSE, message=FALSE}

Table_3 <- df.cln
# Create a column with log(mkt+1)
Table_3$log_return <- log(df.cln$Mkt+1, base = exp(1))

summary(lm(Table_3$log_return~Table_3$TERM, data=df.cln))

# regression with TERM
model <- lm(Table_3$log_return ~ lag(TERM), df.cln)
reg_TERM <- tidy(coeftest(model, NeweyWest(model, lag = 1, prewhite = FALSE)))
# regression with DEF
model <- lm(Table_3$log_return ~ lag(DEF), df.cln)
reg_DEF <- tidy(coeftest(model, NeweyWest(model, lag = 1, prewhite = FALSE)))
# regression with DY
model <- lm(Table_3$log_return ~ lag(DY), df.cln)
reg_DY <- tidy(coeftest(model, NeweyWest(model, lag = 1, prewhite = FALSE)))
# regression with RF
model <- lm(Table_3$log_return ~ lag(RF), df.cln)
reg_RF <- tidy(coeftest(model, NeweyWest(model, lag = 1, prewhite = FALSE)))
# regression with PE
model <- lm(Table_3$log_return ~ lag(PE), df.cln)
reg_PE <- tidy(coeftest(model, NeweyWest(model, lag = 1, prewhite = FALSE)))
# regression with CP
model <- lm(Table_3$log_return ~ lag(CP), df.cln)
reg_CP <- tidy(coeftest(model, NeweyWest(model, lag = 1, prewhite = FALSE)))

#Synthesize data
total <- rbind(reg_TERM[2,],reg_DEF[2,],reg_DY[2,],reg_RF[2,],reg_PE[2,],reg_CP[2,]) # Intercept removed
View(total)
```

# Table 6 replication

```{r, echo=FALSE, warning=FALSE, message=FALSE}
SB25 <- read.csv("data/25_Portfolios_5x5.CSV", header=TRUE, sep=",")
ME25 <- read.csv("data/25_Portfolios_ME_Prior_12_2.CSV", header=TRUE, sep=",")
print(SB25)


```

# Test replication with 5 Portfolio

```{r, echo=FALSE, warning=FALSE, message=FALSE}
monthly5 <- read.csv("data/5 portfolio monthly.csv")
print(monthly5)
summary(gmm(Mkt.RF ~ RF, ~RF, data=monthly5))

# standard approach
g <- function(theta, x) {
  m.1 <- x[,"Mkt.RF"] - theta[1]
  m.z <- m.1*x[,"RF"]
  f <- cbind(m.1, m.z)
  return(f)
}

summary(gmm(g, monthly5, t0=c(0,0), method = "BFGS", control=list(fnscale=1e-8)))
summary(gmm(g, monthly5, t0=c(0,0), method = "BFGS", control=list(fnscale=1e-8), kernel="Bartlett", bw=bwNeweyWest))


```
